<h2>Current Bugs</h2>
<?php echo $this->listToolsForm;
//error_log(print_r(get_class_vars($this), 1));
?>
<?php echo $this->paginationControl($this->paginator,
'Sliding',
'partials/pagination-control.phtml'); ?>
<table class='spreadsheet' border="">
<tr>
<th>&nbsp;</th>
<th>Date</th>
<th>Priority</th>
<th>Status</th>
<th>URL</th>
<th>Submitter</th>
<th>Description</th>
</tr>
<?php echo $this->partialLoop('bug/table-row.phtml', $this->paginator); ?>
</table>

