<!DOCTYPE html>
<html>
<head>
<meta name="language" content="en" />
<meta charset="utf-8"/>
<?php
echo $this->headTitle();
echo $this->headScript();
$this->headLink()->appendStylesheet('/css/default.css');
$this->loadSkin($this->skin);
echo $this->headLink();
//error_log('Headlink: ' . $this->headLink());
?>
</head>
<body>

 <?php echo $this->doctype(); ?>
  <div id="pageWrapper">

    <header id="header">
        <img src="/images/babylon_cms_logo.png" style="position: absolute; right: 100%; top: 40px; margin-right: 20px;" />
    </header>

    <nav id="nav">
        <?php echo $this->layout()->nav;?>&nbsp;
    </nav>

    <aside id="sidebar">

        <nav id="subNav">
          <?php echo $this->layout()->subNav;?>&nbsp;
        </nav>

        <nav id="adminMenu">
          <?php echo $this->layout()->adminMenu;?>&nbsp;
        </nav>

        <div id="userForm">
          <?php echo $this->layout()->userForm;?>&nbsp;
        </div>

    </aside>

    <section id="main">
        <?php echo $this->layout()->content;?>&nbsp;
    </section>

    <section id="footer">
        <p><em>Powered by Zend Framework 1.11</em></p>
    </section>

  </div>

<?php
  echo $this->jQuery()
    ->setVersion('1.5.1')
    ->setUiVersion('1.8.14')
    ->enable()
    ->uiEnable();
?>
</body>
</html>